### ISSUE TITLE
Unsafe Runner fails to handle m2 targeting

### ISSUE THREAD

**Issue by rcurranmoz** [mozilla-platform-ops/android-tools#116]
From the readme here:
```
./safe_runner.py --talk releng-hardware gecko-t-osx-1015-r8 macmini-r8-22,macmini-r8-23,macmini-r8-24 \
  "cd ~/git/ronin_puppet && bolt plan run deploy::apply_no_verify -t SR_HOST.SR_FQDN noop=false -v"
```

It seems like something like this should also work:

```
(android-tools) ➜  worker_health git:(master) ✗ ./unsafe_runner.py --talk releng-hardware gecko-t-osx-1400-m2-staging macmini-m2-13 \
  "xcodes install 15.4"
usage: unsafe_runner.py [-h] [--resume_dir RUN_DIR] [--do-not-randomize] [--talk] [--reboot-host] [--fqdn-postfix FQDN_POSTFIX]
                        host_csv command
unsafe_runner.py: error: unrecognized arguments: macmini-m2-13
zsh: command not found: xcodes install 15.4
```

But it doesn't seem to.

**Comment by aerickson** [comment]
unsafe_runner doesn't take the `provisioner` or `worker_type` arguments.

```bash
(worker_health) powderdry  worker_health git:(master) ✗  ➜  ./safe_runner.py
usage: safe_runner.py [-h] [--resume_dir RUN_DIR] [--do-not-randomize] [--talk] [--reboot-host] [--dont-lift_quarantine] [--fqdn-postfix FQDN_POSTFIX]
                      [--pre_quarantine_additional_host_count COUNT]
                      provisioner worker_type host_csv command
safe_runner.py: error: the following arguments are required: provisioner, worker_type, host_csv, command
(worker_health) powderdry  worker_health git:(master) ✗  ➜  ./unsafe_runner.py                                                                   
usage: unsafe_runner.py [-h] [--resume_dir RUN_DIR] [--do-not-randomize] [--talk] [--reboot-host] [--fqdn-postfix FQDN_POSTFIX] host_csv command
unsafe_runner.py: error: the following arguments are required: host_csv, command
(worker_health) powderdry  worker_health git:(master) ✗  ➜  
```

The command below should work, but I found a bug. 

```
$ ./unsafe_runner.py --talk --fqdn-postfix test.releng.mslv.mozilla.com  macmini-m2-13  "xcodes install 15.4"

                                            .o88o.
                                            888 `"
oooo  oooo  ooo. .oo.    .oooo.o  .oooo.   o888oo   .ooooo.
`888  `888  `888P"Y88b  d88(  "8 `P  )88b   888    d88' `88b
 888   888   888   888  `"Y88b.   .oP"888   888    888ooo888
 888   888   888   888  o.  )88b d8(  888   888    888    .o
 `V88V"V8P' o888o o888o 8""888P' `Y888""8o o888o   `Y8bod8P'

oooo d8b oooo  oooo  ooo. .oo.   ooo. .oo.    .ooooo.  oooo d8b
`888""8P `888  `888  `888P"Y88b  `888P"Y88b  d88' `88b `888""8P
 888      888   888   888   888   888   888  888ooo888  888
 888      888   888   888   888   888   888  888    .o  888
d888b     `V88V"V8P' o888o o888o o888o o888o `Y8bod8P' d888b

Traceback (most recent call last):
  File "/Users/aerickson/git/android-tools/worker_health/./unsafe_runner.py", line 53, in <module>
    runner.main(args)
  File "/Users/aerickson/git/android-tools/worker_health/worker_health/runner.py", line 545, in main
    sr = Runner(hosts=args.hosts, command=args.command, fqdn_prefix=args.fqdn_prefix)
                                                                    ^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'fqdn_prefix'. Did you mean: 'fqdn_postfix'?
```
Will push a fix PR.
